wip

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -302,23 +302,23 @@ jobs:
             echo "Step skipped"
           fi
 
-      - name: Check if any PR have been merged before merging the bump PR
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          if [ "$PR_NUMBER" -gt 0 ]; then
-            # Sometimes the commit is not available immediately after merging the PR, so we wait a bit
-            sleep 5
-            COMMIT_SHA=$(gh api repos/${{ env.KYMA_ENVIRONMENT_BROKER_REPO }}/commits -q '.[1].sha')
-            echo "Latest commit sha: $COMMIT_SHA"
-            echo "Bump sha: ${{ github.sha }}"
-            if [ "$COMMIT_SHA" != "${{ github.sha }}" ]; then
-              echo "::error ::a PR have been merged before merging the bump PR. Don't rerun this workflow. Create a new release with the same version"
-              exit 1 
-          fi
-          else
-            echo "Step skipped"
-          fi   
+#      - name: Check if any PR have been merged before merging the bump PR
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          if [ "$PR_NUMBER" -gt 0 ]; then
+#            # Sometimes the commit is not available immediately after merging the PR, so we wait a bit
+#            sleep 5
+#            COMMIT_SHA=$(gh api repos/${{ env.KYMA_ENVIRONMENT_BROKER_REPO }}/commits -q '.[1].sha')
+#            echo "Latest commit sha: $COMMIT_SHA"
+#            echo "Bump sha: ${{ github.sha }}"
+#            if [ "$COMMIT_SHA" != "${{ github.sha }}" ]; then
+#              echo "::error ::a PR have been merged before merging the bump PR. Don't rerun this workflow. Create a new release with the same version"
+#              exit 1
+#          fi
+#          else
+#            echo "Step skipped"
+#          fi
 
       - name: Save latest commit ref
         id: pull-ref
